export const jobList = [
  {
    title: "Accountant",
    location: "BERLIN, GERMANY",
    category: "ACCOUNTING",
    type: "FULL-TIME",
    contract: "ON-SITE",
  },
  {
    title: "Technical Accounting Specialist",
    location: "STOCKHOLM, SWEDEN",
    category: "ACCOUNTING",
    type: "FULL-TIME",
    contract: "HYBRID",
  },
  {
    title: "Technical Accounting Specialist",
    location: "LONDON, UK",
    category: "ACCOUNTING",
    type: "HYBRID",
    contract: "",
  },
  {
    title: "2nd Line Operational Risk Manager: Third Party",
    location: "LONDON, UK",
    category: "ANALYTICS",
    type: "FULL-TIME",
    contract: "HYBRID",
  },
  {
    title: "AML Data Analyst",
    location: "STOCKHOLM, SWEDEN",
    category: "ANALYTICS",
    type: "FULL-TIME",
    contract: "HYBRID",
  },
  {
    title: "Business Data Analyst - Credit",
    location: "STOCKHOLM, SWEDEN",
    category: "ANALYTICS",
    type: "FULL-TIME",
    contract: "HYBRID",
  },
  {
    title: "Credit Risk Analyst",
    location: "BERLIN, GERMANY",
    category: "ANALYTICS",
    type: "FULL-TIME",
    contract: "HYBRID",
  },
  {
    title: "Financial Controller",
    location: "STOCKHOLM, SWEDEN",
    category: "ANALYTICS",
    type: "FULL-TIME",
    contract: "HYBRID",
  },
  {
    title: "Financial Controller",
    location: "LONDON, UK",
    category: "ANALYTICS",
    type: "FULL-TIME",
    contract: "HYBRID",
  },
  {
    title: "Financial Risk Manager",
    location: "LONDON, UK",
    category: "ANALYTICS",
    type: "FULL-TIME",
    contract: "HYBRID",
  },
  {
    title: "Recoveries Senior Manager",
    location: "LONDON, UK",
    category: "ANALYTICS",
    type: "FULL-TIME",
    contract: "HYBRID",
  },
  {
    title: "PartyX UK Collections & Recoveries Senior Manager",
    location: "STOCKHOLM, SWEDEN",
    category: "ANALYTICS",
    type: "FULL-TIME",
    contract: "HYBRID",
  },
  {
    title: "Product Analyst",
    location: "STOCKHOLM, SWEDEN",
    category: "ANALYTICS",
    type: "FULL-TIME",
    contract: "HYBRID",
  },
  {
    title: "Product Analyst",
    location: "BERLIN, GERMANY",
    category: "ANALYTICS",
    type: "FULL-TIME",
    contract: "HYBRID",
  },
  {
    title: "Risk Manager",
    location: "LONDON, UK",
    category: "ANALYTICS",
    type: "FULL-TIME",
    contract: "HYBRID",
  },
  {
    title: "Senior Analyst",
    location: "STOCKHOLM, SWEDEN",
    category: "ANALYTICS",
    type: "FULL-TIME",
    contract: "HYBRID",
  },
  {
    title: "Senior Analyst",
    location: "BERLIN, GERMANY",
    category: "ANALYTICS",
    type: "FULL-TIME",
    contract: "HYBRID",
  },
  {
    title: "Senior Analyst",
    location: "MADRID, SPAIN",
    category: "ANALYTICS",
    type: "FULL-TIME",
    contract: "HYBRID",
  },
  {
    title: "Senior Analyst - Partner Success Team",
    location: "SAN FRANCISCO, CA, UNITED STATES",
    category: "ANALYTICS",
    type: "FULL-TIME",
    contract: "HYBRID",
  },
  {
    title: "Senior Analyst - Partner Success Team",
    location: "LOS ANGELES, CA, UNITED STATES",
    category: "ANALYTICS",
    type: "FULL-TIME",
    contract: "HYBRID",
  },
  {
    title: "Senior Cash Manager - Treasury",
    location: "STOCKHOLM, SWEDEN",
    category: "ANALYTICS",
    type: "FULL-TIME",
    contract: "HYBRID",
  },
  {
    title: "Senior Cash Manager - Treasury",
    location: "LONDON, UK",
    category: "ANALYTICS",
    type: "FULL-TIME",
    contract: "HYBRID",
  },
  {
    title: "Senior Credit Risk Analyst",
    location: "STOCKHOLM, SWEDEN",
    category: "ANALYTICS",
    type: "FULL-TIME",
    contract: "ON-SITE",
  },
  {
    title: "Senior Data Analyst - Customer Service",
    location: "STOCKHOLM, SWEDEN",
    category: "ANALYTICS",
    type: "FULL-TIME",
    contract: "HYBRID",
  },
  {
    title: "Senior Product Analyst",
    location: "MILAN, ITALY",
    category: "ANALYTICS",
    type: "FULL-TIME",
    contract: "HYBRID",
  },
  {
    title: "Senior Product Analyst",
    location: "STOCKHOLM, SWEDEN",
    category: "ANALYTICS",
    type: "FULL-TIME",
    contract: "HYBRID",
  },
  {
    title: "Senior Product Analyst",
    location: "BERLIN, GERMANY",
    category: "ANALYTICS",
    type: "FULL-TIME",
    contract: "HYBRID",
  },
];
