export const events = [
  {
    title: "Party 1",
    img: "https://via.placeholder.com/150?text=Party+1",
    price: 100,
    desc: "Party description 1",
    userName: "John Doe",
    userPhoto: "https://via.placeholder.com/50?text=J",
  },
  {
    title: "Party 2",
    img: "https://via.placeholder.com/150?text=Party+2",
    price: 150,
    desc: "Party description 2",
    userName: "Jane Smith",
    userPhoto: "https://via.placeholder.com/50?text=JS",
  },
  {
    title: "Party 3",
    img: "https://via.placeholder.com/150?text=Party+3",
    price: 90,
    desc: "Party description 3",
    userName: "Mike Johnson",
    userPhoto: "https://via.placeholder.com/50?text=MJ",
  },
  {
    title: "Party 4",
    img: "https://via.placeholder.com/150?text=Party+4",
    price: 120,
    desc: "Party description 4",
    userName: "Emily Brown",
    userPhoto: "https://via.placeholder.com/50?text=EB",
  },
  {
    title: "Party 5",
    img: "https://via.placeholder.com/150?text=Party+5",
    price: 80,
    desc: "Party description 5",
    userName: "Chris White",
    userPhoto: "https://via.placeholder.com/50?text=CW",
  },
  {
    title: "Party 6",
    img: "https://via.placeholder.com/150?text=Party+6",
    price: 170,
    desc: "Party description 6",
    userName: "Ashley Black",
    userPhoto: "https://via.placeholder.com/50?text=AB",
  },
  {
    title: "Party 7",
    img: "https://via.placeholder.com/150?text=Party+7",
    price: 110,
    desc: "Party description 7",
    userName: "Matthew Green",
    userPhoto: "https://via.placeholder.com/50?text=MG",
  },
  {
    title: "Party 8",
    img: "https://via.placeholder.com/150?text=Party+8",
    price: 140,
    desc: "Party description 8",
    userName: "Ava Blue",
    userPhoto: "https://via.placeholder.com/50?text=AB",
  },
  {
    title: "Party 9",
    img: "https://via.placeholder.com/150?text=Party+9",
    price: 130,
    desc: "Party description 9",
    userName: "Liam Yellow",
    userPhoto: "https://via.placeholder.com/50?text=LY",
  },
  {
    title: "Party 10",
    img: "https://via.placeholder.com/150?text=Party+10",
    price: 60,
    desc: "Party description 10",
    userName: "Sophia Purple",
    userPhoto: "https://via.placeholder.com/50?text=SP",
  },
];
