export const events = [
  {
    title: "Sunday Brunch",
    img: "https://cdn.pixabay.com/photo/2017/08/03/21/48/drinks-2578446_1280.jpg",
    currency: "SEK",
    price: 100,
    desc: "Lose yourself to the mellifluous rhythms of jazz as the sun sets. Cocktail attire recommended.",
    userName: "John Doe",
    userPhoto: "https://via.placeholder.com/50?text=J",
  },
  {
    title: "Vintage Wine Gala",
    img: "https://cdn.pixabay.com/photo/2018/07/04/00/19/champagne-3515140_1280.jpg",
    currency: "SEK",
    price: 150,
    desc: "For the wine aficionados! Come taste rare and exotic wines from around the globe.",
    userName: "Jane Smith",
    userPhoto: "https://via.placeholder.com/50?text=JS",
  },
  {
    title: "Smooth Electronics & Conversations",
    img: "https://cdn.pixabay.com/photo/2016/11/22/19/15/hand-1850120_1280.jpg",
    currency: "SEK",
    price: 90,
    desc: "Mingle with fellow beer lovers, and let the conversations flow as smoothly as our on-tap selections.",
    userName: "Mike Johnson",
    userPhoto: "https://via.placeholder.com/50?text=MJ",
  },
  {
    title: "Masquerade Mystique",
    img: "https://cdn.pixabay.com/photo/2016/11/23/13/45/celebration-1852926_1280.jpg",
    currency: "SEK",
    price: 120,
    desc: "A night of secrets and allure. Don your masks and let the mystery ensue.",
    userName: "Emily Brown",
    userPhoto: "https://via.placeholder.com/50?text=EB",
  },
  {
    title: "Art & Aperitifs",
    img: "https://cdn.pixabay.com/photo/2018/06/17/10/38/artist-3480274_1280.jpg",
    currency: "SEK",
    price: 80,
    desc: "For the love of art and wine. Explore handpicked art exhibits while sipping on curated cocktails.",
    userName: "Chris White",
    userPhoto: "https://via.placeholder.com/50?text=CW",
  },
  {
    title: "Electro Nights",
    img: "https://cdn.pixabay.com/photo/2019/12/18/04/11/dj-4702977_1280.jpg",
    currency: "SEK",
    price: 170,
    desc: "Feel the beat drop and let the electronic vibes take over. Perfect for EDM enthusiasts.",
    userName: "Ashley Black",
    userPhoto: "https://via.placeholder.com/50?text=AB",
  },
  {
    title: "Tropical Beach Bash",
    img: "https://via.placeholder.com/150?text=Party+7",
    currency: "SEK",
    price: 110,
    desc: "Bring out the beachwear! Groove to tropical tunes and sip on exotic tiki cocktails.",
    userName: "Matthew Green",
    userPhoto: "https://via.placeholder.com/50?text=MG",
  },
];
