export const festivals = [
  {
    title: "Rock Paradise",
    img: "https://cdn.pixabay.com/photo/2016/11/29/07/36/audience-1868137_1280.jpg",
    price: 150,
    currency: "SEK",
    desc: "A massive rock festival featuring the world's top rock bands.",
    userName: "John Doe",
    userPhoto: "https://via.placeholder.com/50?text=JD",
    date: "Oct 11",
    time: "16:00 - 18:30",
  },
  {
    title: "Jazz and Blues Fest",
    img: "https://cdn.pixabay.com/photo/2017/07/21/23/57/concert-2527495_1280.jpg",
    price: 120,
    currency: "SEK",
    desc: "Dive deep into the rhythms of jazz and blues from global artists.",
    userName: "Alice Johnson",
    userPhoto: "https://example.com/users/alice.jpg",
    date: "Oct 15",
    time: "17:00 - 19:30",
  },
  {
    title: "Country Music Bonanza",
    img: "https://cdn.pixabay.com/photo/2016/11/22/19/15/audience-1850119_1280.jpg",
    price: 90,
    currency: "SEK",
    desc: "Enjoy the twang and tales of country music under the open sky.",
    userName: "Bob Dylan",
    userPhoto: "https://example.com/users/bob.jpg",
    date: "Oct 26",
    time: "20:00 - 22:30",
  },
  {
    title: "Electro Beat Drop",
    img: "https://cdn.pixabay.com/photo/2016/11/29/06/17/audience-1867754_1280.jpg",
    price: 180,
    currency: "SEK",
    desc: "Dance away in this electric festival pulsating with energy.",
    userName: "Charlie Puth",
    userPhoto: "https://example.com/users/charlie.jpg",
    date: "Oct 12",
    time: "22:00 - 23:30",
  },
  {
    title: "Classical Echoes",
    img: "https://cdn.pixabay.com/photo/2016/11/23/18/05/concert-1854113_1280.jpg",
    price: 200,
    currency: "SEK",
    desc: "Experience the serene sounds of classical music in a tranquil setting.",
    userName: "Diana Ross",
    userPhoto: "https://example.com/users/diana.jpg",
    date: "Oct 15",
    time: "21:00 - 0:30",
  },
  {
    title: "Reggae Rhythms",
    img: "https://cdn.pixabay.com/photo/2017/04/10/16/55/live-music-2219036_1280.jpg",
    price: 80,
    currency: "SEK",
    desc: "Relax and feel the vibes of the island rhythms in this reggae fest.",
    userName: "Frank Ocean",
    userPhoto: "https://example.com/users/frank.jpg",
    date: "Oct 15",
    time: "16:00 - 2:30",
  },
];

export default festivals;
